"use client";

import { type FormEvent, useEffect, useState } from "react";
import { ArrowRight, Check, Clipboard, Download, Loader2, RefreshCw, Share2, Sparkles, Target, TriangleAlert } from "lucide-react";

type Roadmap = {
  title: string; summary: string; careerOverview: string; estimatedHiringReadinessScore: number; isRealistic: boolean; reason: string; recommendedDuration: string; currentSkills: string[]; strengths: string[];
  skillGaps: { skill: string; importance: "High" | "Medium" | "Low"; reason: string }[];
  learningResources: { skill: string; freeCourse: string; youtube: string; documentation: string; practice: string; certification?: string }[]; recommendedBooks: string[];
  recommendedProjects: { title: string; difficulty: string; skillsLearned: string[]; estimatedDuration: string; portfolioValue: string; description: string }[];
  resumeImprovements: string[]; linkedInImprovements: { headline: string; about: string; skillsToAdd: string[]; projectsToShowcase: string[] };
  interviewPrep: { behavioral: string[]; technical: string[]; roleSpecific: string[]; tips: string[] };
  dailySchedule: string[]; weeklyMilestones: string[]; thirtyDayPlan: string[]; sixtyDayPlan: string[]; ninetyDayPlan: string[]; finalChecklist: string[]; nextSteps: string[]; isFallback?: boolean;
};

const inputClass = "w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white placeholder:text-zinc-600 outline-none transition focus:border-cyan-400/60 focus:ring-2 focus:ring-cyan-400/15 disabled:opacity-60";
const stages = ["Analyzing your background…", "Understanding your career goals…", "Finding skill gaps…", "Researching your roadmap…", "Preparing your interview plan…", "Building your personalized roadmap…", "Almost ready…"];
const statuses = [["🎓", "Student"], ["💼", "Working Professional"], ["🔄", "Career Switcher"], ["🚀", "Entrepreneur"], ["🧑‍💻", "Freelancer"], ["🎯", "Fresher"]] as const;
const roles = ["Associate Product Manager", "Product Manager", "Senior Product Manager", "AI Product Manager", "Growth Product Manager", "Software Engineer", "Frontend Developer", "Backend Developer", "Full Stack Developer", "UX Designer", "Data Analyst", "Business Analyst", "Marketing Manager", "Digital Marketing", "Sales Manager", "HR Manager", "Machine Learning Engineer", "DevOps Engineer", "Cloud Engineer", "Cyber Security Engineer"];
const skills = ["Python", "SQL", "Excel", "Communication", "Leadership", "Marketing", "React", "Node.js", "Next.js", "Java", "C++", "Product Management", "Wireframing", "Figma", "Analytics", "Public Speaking", "Problem Solving", "Business Strategy"];

function List({ items }: { items: string[] }) { return <ul className="space-y-2 text-sm leading-6 text-zinc-300">{items.map((item, index) => <li key={`${item}-${index}`} className="flex gap-2"><Check className="mt-1 h-4 w-4 shrink-0 text-emerald-400" />{item}</li>)}</ul>; }
function Panel({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <section className={`glass-card rounded-2xl p-5 print:border-zinc-300 print:bg-white ${className}`}><h3 className="mb-4 text-lg font-semibold text-white print:text-zinc-900">{title}</h3>{children}</section>; }

function Results({ roadmap, onReset, profile }: { roadmap: Roadmap; onReset: () => void; profile: { currentStatus: string; currentRole: string; targetRole: string; experienceLevel: string; duration: string } }) {
  const [copied, setCopied] = useState(false);
  const share = async () => { const content = `${roadmap.title}\n\n${roadmap.summary}\n\nReadiness: ${roadmap.estimatedHiringReadinessScore}/100`; try { if (navigator.share) await navigator.share({ title: roadmap.title, text: content, url: location.href }); else { await navigator.clipboard.writeText(location.href); setCopied(true); } } catch { /* sharing was cancelled */ } };
  const copySummary = async () => { await navigator.clipboard.writeText(`${roadmap.title}\n\n${roadmap.summary}\n\n${roadmap.careerOverview}`); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  const importance = { High: "bg-rose-400/15 text-rose-200", Medium: "bg-amber-400/15 text-amber-200", Low: "bg-cyan-400/15 text-cyan-200" };
  return <div id="roadmap-results" className="mt-8 space-y-5 animate-fade-in">
    <div className="hidden print:block print:border-b print:border-zinc-300 print:pb-5"><div className="flex items-start justify-between"><div><p className="text-xl font-bold text-zinc-900">GeniusGo</p><p className="mt-1 text-sm text-zinc-600">Personalized career roadmap</p></div><p className="text-xs text-zinc-500">Generated {new Date().toLocaleDateString()}</p></div><p className="mt-4 text-xs text-zinc-700">Background: {profile.currentRole || profile.currentStatus} · Target: {profile.targetRole} · {profile.experienceLevel} · {profile.duration}</p></div>
    <section className="rounded-2xl border border-cyan-400/20 bg-cyan-400/[.05] p-6 print:border-zinc-300 print:bg-white">
      <div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full bg-violet-400/10 px-3 py-1 text-xs text-violet-200 print:text-violet-800"><Sparkles className="h-3.5 w-3.5" />{roadmap.isFallback ? "GeniusGo starter roadmap" : "Personalized by Gemini"}</span><h2 className="mt-3 text-2xl font-bold text-white print:text-zinc-900">{roadmap.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-300 print:text-zinc-700">{roadmap.summary}</p></div><div className="flex flex-wrap gap-2 print:hidden"><button onClick={share} className="action-button"><Share2 className="h-4 w-4" />Share</button><button onClick={copySummary} className="action-button"><Clipboard className="h-4 w-4" />{copied ? "Copied" : "Copy summary"}</button><button onClick={() => window.print()} className="action-button"><Download className="h-4 w-4" />Save PDF</button><button onClick={onReset} className="action-button"><RefreshCw className="h-4 w-4" />New</button></div></div>
    </section>
    <div className="grid gap-5 md:grid-cols-2"><Panel title="Hiring readiness"><div className="flex items-end justify-between"><strong className="text-4xl text-white print:text-zinc-900">{roadmap.estimatedHiringReadinessScore}<small className="text-base text-zinc-400">/100</small></strong><span className="text-sm text-zinc-400">Estimated today</span></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{ width: `${roadmap.estimatedHiringReadinessScore}%` }} /></div><p className="mt-4 text-sm text-zinc-300 print:text-zinc-700">{roadmap.careerOverview}</p></Panel><Panel title="Reality check"><div className={`rounded-xl p-4 text-sm leading-6 ${roadmap.isRealistic ? "bg-emerald-400/10 text-emerald-100" : "bg-amber-400/10 text-amber-100"}`}><div className="mb-1 flex gap-2 font-semibold">{!roadmap.isRealistic && <TriangleAlert className="h-5 w-5" />}{roadmap.isRealistic ? "Achievable with focus" : "Not realistic as stated"}</div>{roadmap.reason}<p className="mt-2 font-semibold">Recommended timeline: {roadmap.recommendedDuration}</p></div></Panel></div>
    <div className="grid gap-5 lg:grid-cols-2"><Panel title="Strengths & skill gap analysis"><div className="mb-4 flex flex-wrap gap-2">{roadmap.currentSkills.map((skill) => <span key={skill} className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs text-emerald-200">{skill}</span>)}</div><List items={roadmap.strengths} /><div className="mt-4 space-y-3">{roadmap.skillGaps.map((gap) => <div key={gap.skill} className="rounded-xl border border-white/10 bg-black/10 p-3"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-white print:text-zinc-900">{gap.skill}</strong><span className={`rounded-full px-2 py-1 text-xs ${importance[gap.importance]}`}>{gap.importance}</span></div><p className="mt-1 text-xs leading-5 text-zinc-400">{gap.reason}</p></div>)}</div></Panel><Panel title="Learning resources & books"><div className="space-y-4">{roadmap.learningResources.map((resource) => <article key={resource.skill} className="border-b border-white/10 pb-3 last:border-0"><strong className="text-sm text-white print:text-zinc-900">{resource.skill}</strong><dl className="mt-2 grid gap-1 text-xs text-zinc-400"><div><dt className="inline text-zinc-300">Free course: </dt><dd className="inline">{resource.freeCourse}</dd></div><div><dt className="inline text-zinc-300">YouTube: </dt><dd className="inline">{resource.youtube}</dd></div><div><dt className="inline text-zinc-300">Docs: </dt><dd className="inline">{resource.documentation}</dd></div><div><dt className="inline text-zinc-300">Practice: </dt><dd className="inline">{resource.practice}</dd></div></dl></article>)}</div><div className="mt-4 border-t border-white/10 pt-3"><List items={roadmap.recommendedBooks} /></div></Panel></div>
    <Panel title="Five projects that prove your readiness"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{roadmap.recommendedProjects.map((project) => <article key={project.title} className="rounded-xl border border-white/10 bg-black/10 p-4"><div className="flex items-start justify-between gap-2"><h4 className="font-semibold text-white print:text-zinc-900">{project.title}</h4><span className="rounded-full bg-violet-400/10 px-2 py-1 text-xs text-violet-200">{project.difficulty}</span></div><p className="mt-2 text-sm leading-6 text-zinc-300 print:text-zinc-700">{project.description}</p><p className="mt-3 text-xs text-cyan-200">{project.estimatedDuration} · {project.portfolioValue}</p><div className="mt-3 flex flex-wrap gap-1">{project.skillsLearned.map((skill) => <span key={skill} className="rounded bg-white/5 px-2 py-1 text-xs text-zinc-300">{skill}</span>)}</div></article>)}</div></Panel>
    <div className="grid gap-5 lg:grid-cols-2"><Panel title="Resume improvements"><List items={roadmap.resumeImprovements} /></Panel><Panel title="LinkedIn improvements"><p className="text-sm font-medium text-cyan-200">{roadmap.linkedInImprovements.headline}</p><p className="mt-3 text-sm leading-6 text-zinc-300">{roadmap.linkedInImprovements.about}</p><p className="mt-3 text-xs text-zinc-400">Add: {roadmap.linkedInImprovements.skillsToAdd.join(", ")}</p></Panel></div>
    <Panel title="Interview preparation"><div className="grid gap-5 md:grid-cols-3">{[["Behavioral", roadmap.interviewPrep.behavioral], ["Technical", roadmap.interviewPrep.technical], ["Role-specific", roadmap.interviewPrep.roleSpecific]].map(([title, items]) => <div key={String(title)}><h4 className="mb-2 text-sm font-semibold text-white print:text-zinc-900">{title}</h4><List items={items as string[]} /></div>)}</div><div className="mt-4 border-t border-white/10 pt-4"><List items={roadmap.interviewPrep.tips} /></div></Panel>
    <div className="grid gap-5 md:grid-cols-2"><Panel title="Daily schedule"><List items={roadmap.dailySchedule} /></Panel><Panel title="Weekly milestones"><List items={roadmap.weeklyMilestones} /></Panel></div>
    <div className="grid gap-5 lg:grid-cols-3"><Panel title="First 30 days"><List items={roadmap.thirtyDayPlan} /></Panel><Panel title="Days 31–60"><List items={roadmap.sixtyDayPlan} /></Panel><Panel title="Days 61–90"><List items={roadmap.ninetyDayPlan} /></Panel></div><div className="grid gap-5 md:grid-cols-2"><Panel title="Final launch checklist"><List items={roadmap.finalChecklist} /></Panel><Panel title="Next steps"><List items={roadmap.nextSteps} /></Panel></div><p className="hidden text-center text-xs text-zinc-500 print:block">Generated using GeniusGo · https://geniusgo.vercel.app</p>
  </div>;
}

export default function HeroForm() {
  const [form, setForm] = useState({ currentStatus: "Student", currentRole: "", experienceLevel: "Beginner", targetRole: "", currentSkills: "", duration: "90 days" }); const [selectedSkills, setSelectedSkills] = useState<string[]>([]); const [skillSearch, setSkillSearch] = useState(""); const [customTimeline, setCustomTimeline] = useState(""); const [roadmap, setRoadmap] = useState<Roadmap | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [stage, setStage] = useState(0);
  useEffect(() => { if (!loading) return; const id = window.setInterval(() => setStage((current) => Math.min(current + 1, stages.length - 1)), 2300); return () => window.clearInterval(id); }, [loading]);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  function toggleSkill(skill: string) { setSelectedSkills((current) => current.includes(skill) ? current.filter((item) => item !== skill) : [...current, skill]); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setLoading(true); setStage(0); const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 135_000); const payload = { ...form, duration: form.duration === "Custom" ? customTimeline : form.duration, currentSkills: selectedSkills.join(", ") }; try { const response = await fetch("/api/roadmap", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload), signal: controller.signal }); const data = await response.json().catch(() => ({})); if (!response.ok || !data.roadmap) throw new Error(data.error || "We couldn’t create that roadmap. Please try again."); setRoadmap(data.roadmap); setTimeout(() => document.getElementById("roadmap-results")?.scrollIntoView({ behavior: "smooth", block: "start" }), 50); } catch { setError("Your roadmap couldn’t be generated right now. Please retry in a moment."); } finally { window.clearTimeout(timeout); setLoading(false); } }
  return <div className="mx-auto w-full max-w-5xl"><form onSubmit={submit} className="rounded-3xl border border-white/10 bg-white/[.04] p-5 shadow-2xl shadow-black/30 backdrop-blur-xl sm:p-8"><div className="space-y-7">
    <fieldset disabled={loading}><legend className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Your current background</legend><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{statuses.map(([icon, label]) => <button type="button" key={label} onClick={() => update("currentStatus", label)} className={`rounded-xl border p-3 text-left transition hover:-translate-y-0.5 ${form.currentStatus === label ? "border-cyan-400/60 bg-cyan-400/10" : "border-white/10 bg-black/10 hover:border-white/25"}`}><span className="block text-lg">{icon}</span><span className="mt-1 block text-xs font-medium text-white">{label}</span></button>)}</div><label className="mt-4 block text-xs font-semibold uppercase tracking-wider text-zinc-400">Or enter your current role<input value={form.currentRole} onChange={(e) => update("currentRole", e.target.value)} maxLength={120} placeholder="Software Engineer, Teacher, Marketing Executive…" className={`${inputClass} mt-2`} /></label></fieldset>
    <div className="grid gap-6 lg:grid-cols-2"><label className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Target role<input list="role-suggestions" value={form.targetRole} onChange={(e) => update("targetRole", e.target.value)} required maxLength={120} placeholder="Search or enter any role…" className={`${inputClass} mt-2`} /><datalist id="role-suggestions">{roles.map((role) => <option key={role} value={role} />)}</datalist><span className="mt-2 block normal-case text-zinc-500">Choose a suggestion or enter a custom role.</span></label><fieldset><legend className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Experience</legend><div className="mt-2 grid grid-cols-3 gap-2">{["Beginner", "Intermediate", "Advanced"].map((level) => <button type="button" key={level} onClick={() => update("experienceLevel", level)} className={`rounded-xl border px-3 py-3 text-sm font-medium transition ${form.experienceLevel === level ? "border-violet-400/60 bg-violet-400/10 text-white" : "border-white/10 bg-white/5 text-zinc-400"}`}>{level}</button>)}</div></fieldset></div>
    <fieldset><legend className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Timeline</legend><div className="mt-2 grid grid-cols-3 gap-2 sm:grid-cols-6">{["30 Days", "60 Days", "90 Days", "6 Months", "1 Year", "2 Years", "Custom"].map((time) => <button type="button" key={time} onClick={() => update("duration", time)} className={`rounded-xl border px-2 py-3 text-xs font-medium transition ${form.duration === time ? "border-amber-400/60 bg-amber-400/10 text-white" : "border-white/10 bg-white/5 text-zinc-400"}`}>{time}</button>)}</div>{form.duration === "Custom" && <input value={customTimeline} onChange={(e) => setCustomTimeline(e.target.value)} required placeholder="e.g. 4 months" className={`${inputClass} mt-3`} />}</fieldset>
    <fieldset><legend className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Current skills</legend><div className="mt-3 rounded-2xl border border-white/10 bg-black/10 p-3"><div className="flex flex-wrap gap-2">{selectedSkills.map((skill) => <button type="button" key={skill} onClick={() => toggleSkill(skill)} className="rounded-full bg-cyan-400/15 px-3 py-1.5 text-xs text-cyan-100">{skill} ×</button>)}</div><input value={skillSearch} onChange={(e) => setSkillSearch(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && skillSearch.trim()) { e.preventDefault(); toggleSkill(skillSearch.trim()); setSkillSearch(""); } }} placeholder="Search skills or type one and press Enter" className="mt-3 w-full bg-transparent text-sm text-white outline-none placeholder:text-zinc-600" /></div><div className="mt-3 flex flex-wrap gap-2">{skills.filter((skill) => skill.toLowerCase().includes(skillSearch.toLowerCase())).map((skill) => <button type="button" key={skill} onClick={() => toggleSkill(skill)} className={`rounded-full border px-3 py-1.5 text-xs transition ${selectedSkills.includes(skill) ? "border-cyan-400/50 bg-cyan-400/10 text-cyan-100" : "border-white/10 text-zinc-400 hover:text-white"}`}>{skill}</button>)}</div></fieldset>
  </div>{loading && <div className="mt-5 rounded-xl border border-violet-400/20 bg-violet-400/10 p-4"><div className="flex items-center gap-3 text-sm text-violet-100"><Loader2 className="h-5 w-5 animate-spin" />{stages[stage]}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-gradient-to-r from-violet-500 to-cyan-400 transition-all" style={{ width: `${((stage + 1) / stages.length) * 100}%` }} /></div></div>}{error && <div role="alert" className="mt-5 flex items-center justify-between gap-3 rounded-xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-100">{error}<button type="submit" className="underline">Retry</button></div>}<button disabled={loading || !form.targetRole.trim() || !selectedSkills.length || (form.duration === "Custom" && !customTimeline.trim())} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan-500 via-blue-500 to-violet-500 px-6 py-4 text-sm font-bold text-white shadow-xl shadow-cyan-950/40 transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60">{loading ? <><Loader2 className="h-5 w-5 animate-spin" />Building your roadmap</> : <><Target className="h-5 w-5" />Generate my roadmap<ArrowRight className="h-5 w-5" /></>}</button></form>{roadmap && <Results roadmap={roadmap} onReset={() => setRoadmap(null)} profile={{ ...form, duration: form.duration === "Custom" ? customTimeline : form.duration }} />}</div>;
}
